dist: xenial
language: python
python:
  - "3.7.1"

jobs:
  include:
    - stage: Deploy to PyPi on new releases
      script: skip
      deploy:
        - provider: pypi
          user: $PYPI_USER
          password: $PYPI_PASS
          on:
            tags: true
      if: tag IS present
